name: autorelease

on:
  push:
    branches:
      - alpha
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Get Local Version
        id: local_version
        run: echo "VERSION=$(cat ${{ github.workspace }}/package.json | jq '.version')" >> $GITHUB_OUTPUT
      - name: Print Version
        run: echo ${{ steps.local_version.outputs.VERSION }}
      - name: Print Has Version
        run: echo "$(npm view @lspriv/wx-calendar@${{ steps.local_version.outputs.VERSION }})"
      - name: Print Has Pre
        run: echo "${{ contains(fromJSON('["alphs", "beta", "rc"]'), steps.local_version.outputs.VERSION) }}"
      - name: Echo Github
        run: |
          echo "base_ref ${{ github.base_ref }}"
          echo "head_ref ${{ github.head_ref }}"
          echo "ref ${{ github.ref }}"
          echo "workspace ${{ github.workspace }}"
      - name: Publish to npm
        run: |
          if [[ $(npm view @lspriv/wx-calendar@${{ steps.local_version.outputs.VERSION }}) ]] && [[ contains(fromJSON('["alphs", "beta", "rc"]'), steps.local_version.outputs.VERSION) ]]; then
            echo "yes"
            exit 1
          else
            echo "no"
          fi
