name: autorelease

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Get Local Version
        id: local_version
        run: echo "VERSION=$(cat ${{ github.workspace }}/package.json | jq '.version')" >> $GITHUB_OUTPUT
      - name: Print Version
        run: echo ${{ steps.local_version.outputs.VERSION }}
      - name: Print Has Version
        run: echo "$(npm view @lspriv/wx-calendar@${{ steps.local_version.outputs.VERSION }})"
      - name: Print Has Pre
        run: echo "${{ contains(steps.local_version.outputs.VERSION, 'alpha') || contains(steps.local_version.outputs.VERSION, 'beta') || contains(steps.local_version.outputs.VERSION, 'rc') }}"
      - name: Echo Github
        run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ contains(github.event.head_commit.message, 'Merge pull request') && contains(github.event.head_commit.message, 'from lspriv/develop') }}
      - name: Publish to npm
        run: |
          if [[ $(npm view @lspriv/wx-calendar@${{ steps.local_version.outputs.VERSION }}) ]] || [[ ${{ contains(steps.local_version.outputs.VERSION, 'alpha') || contains(steps.local_version.outputs.VERSION, 'beta') || contains(steps.local_version.outputs.VERSION, 'rc') }} ]]; then
            echo "yes"
          else
            echo "no"
          fi
