name: autorelease

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
      
      - name: Checkout Repository
        if: ${{ steps.release.outputs.prs_created }}
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.prs_created }}
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to npm
        if: ${{ steps.release.outputs.prs_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npm run build
          npm publish --access public
